####################################################
#  Model
####################################################

#GruLabeler.embedding = @ConvEmbedding() #Embedding
#GruLabeler.embedding = @Embedding()
#
#model:
#  class_path: deepgen.models.GruLabeler
#  init_args:
#    input_size: 1
#    n_class: 32
#    hidden_size: 32
#    num_layers: 4
#  embedding:
#    class_path: deepgen.models.NoEmbedding
#  predictor:
#    class_path: deepgen.models.Predictor
#    init_args:
#      d_model: 64
#      dropout: 0.1
#      n_class: 32

#class_path: deepgen.models.GruLabeler
#init_args:
#  input_size: 1
#  n_class: 32
#  hidden_size: 32
#  num_layers: 4
#embedding:
#  class_path: deepgen.models.NoEmbedding
#predictor:
#  class_path: deepgen.models.Predictor
#  init_args:
#    d_model: 64
#    dropout: 0.1
#    n_class: 32

class_path: deepgen.models.Mock
init_args:
  a: 1
  b: 2
  c: 3

#a: 1
#b: 2
#c: 3


#
#embedding:
#  class_path: deepgen.models.NoEmbedding
#
#
#ConvEmbedding:
#  n_layers: 4
#  in_channels: 1
#  out_channels: 32
#  kernel_size: 11
#  stride: 1